### ISSUE TITLE
Fixing broken links in website documentation references

### ISSUE THREAD

**Issue by cpeppler01** [kauailabs/allwpilib#23]
There are a couple of links on the web page for the beta documentation that could be updated for other beta users:

[Link to page with broken links](https://pdocs.kauailabs.com/vmx-pi/advanced/vmx-pi-wpi-library-beta/beta-documentation/current-frc-documentation-references/)

**FRC Java Programming References**, Should point to:
https://first.wpi.edu/FRC/roborio/release/docs/java/index.html
(Note, this is for WPILib API 2020.3.2-23-gf6df921) 

**Instructions on installing VSCode and Programming a FRC Robot in Java** Should point to:
https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/wpilib-setup.html

**FRC C++ Programming Reference** Should point to:
https://first.wpi.edu/FRC/roborio/release/docs/cpp/index.html
(Note: WPILibC++  2020.3.2-23-gf6df921)

**FRC Driver Station Powered by NI LabVIEW** should point to:
https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/frc-game-tools.html
or
https://docs.wpilib.org/en/stable/docs/software/driverstation/driver-station.html

**Running your Benchtop Test Program** should point to:
https://docs.wpilib.org/en/stable/docs/getting-started/running-a-benchtop/index.html

In general these references should point forward into the http://docs.wpilib.org
locations, since they've all been moved.

**Comment by kauailabs** [comment]
Many thanks for the thorough review and feedback.  This referred-to page has been updated as you've suggested.
