### ISSUE TITLE
Analog Input HAL error

### ISSUE THREAD

**Issue by KadenK** [kauailabs/allwpilib#4]
A simple program that reads the value of an Analog input (infrared distance sensor) compiles and deploys successfully, but does not run properly.

Program that threw the error:

```
public class Infrared extends TimedRobot {

    AnalogInput sensor = new AnalogInput(1);

  @Override
  public void teleopPeriodic() {

    int value = sensor.getValue();

    System.out.println("Value:  " + value);

  }
}
```

Error presented by Pi logs at /var/local/kauailabs/logs/FRC_UserProgram.log

> ********** Robot program starting **********
> Default disabledInit() method... Override me!
> Default disabledPeriodic() method... Override me!
> Error at frc.robot.Main.main(Main.java:27): Unhandled exception: edu.wpi.first.hal.util.UncleanStatusException:  Code: -1098. HAL: A handle parameter was passed incorrectly
> 	at edu.wpi.first.hal.AnalogJNI.getAnalogAverageVoltage(Native Method)
> 	at edu.wpi.first.wpilibj.AnalogInput.getAverageVoltage(AnalogInput.java:108)
> 	at edu.wpi.first.wpilibj.smartdashboard.SendableBuilderImpl.lambda$addDoubleProperty$3(SendableBuilderImpl.java:242)
> 	at edu.wpi.first.wpilibj.smartdashboard.SendableBuilderImpl.updateTable(SendableBuilderImpl.java:95)
> 	at edu.wpi.first.wpilibj.livewindow.LiveWindow.updateValues(LiveWindow.java:290)
> 	at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:263)
> 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:81)
> 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:263)
> 	at frc.robot.Main.main(Main.java:27)
> 
> Warning at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:274): Robots should not quit, but yours did!
> Error at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:276): The startCompetition() method (or methods called by it) should have handled the exception above.

**Comment by kauailabs** [comment]
Fixed in v2019.4.1-vmxpi-beta-9.
