### ISSUE TITLE
Firmware installs in <username>\vmx-pi\firmware\, not <username>\navx-micro\firmware

### ISSUE THREAD

**Issue by cecilialau6776** [kauailabs/allwpilib#6]
Firmware installs in <username>\vmx-pi\firmware instead of <username>\navx-micro\firmware as stated on the "Updating Firmware" page.
![image](https://user-images.githubusercontent.com/46845938/61191638-b1293700-a67a-11e9-9981-134044f597ac.png)
(from https://pdocs.kauailabs.com/vmx-pi/support/updating-firmware/)
![image](https://user-images.githubusercontent.com/46845938/61191663-0402ee80-a67b-11e9-86ee-29f6d8388100.png)

**Comment by kauailabs** [comment]
Nice catch, thanks for the help!
