### ISSUE TITLE
"wifiAPSetup.sh" appears to be "setupWifiAP.sh"

### ISSUE THREAD

**Issue by cecilialau6776** [kauailabs/allwpilib#7]
The “wifiAPSetup.sh” script doesn't seem to exist on the pi (with the pre-configured image), and seems to be "setupWifiAP.sh" in /usr/local/vmxpi-frc/networking.
![image](https://user-images.githubusercontent.com/46845938/61193570-2b14ec80-a68a-11e9-8bfb-0e38ec204c23.png)
(from https://pdocs.kauailabs.com/vmx-pi/advanced/vmx-pi-wpi-library-beta/beta-documentation/raspberry-pi-network-configuration-for-frc/)

**Comment by kauailabs** [comment]
Another good find - thanks again.
